# $OpenBSD: $

COMMENT =	print json in an line-oriented format

V =	1.2
DISTNAME =	flattenjs-${V}

CATEGORIES =	sysutils
HOMEPAGE =	https://github.com/eradman/flattenjs
MAINTAINER =	Eric Radman <ericshane@eradman.com>

# ISC
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =	http://eradman.com/ephemeralpg/code/ \
		https://github.com/eradman/flattenjs/archive/${V}/

FAKE_FLAGS =	DESTDIR=""

TEST_TARGET =	test

.include <bsd.port.mk>
