GH_ACCOUNT=		duckdb
GH_PROJECT=		duckdb
GH_TAGNAME=		v1.3.2

COMMENT=		analytical in-process SQL database management system
CATEGORIES=		databases devel

# MIT
PERMIT_PACKAGE=		Yes

WANTLIB=		${COMPILER_LIBCXX} m pthread

# C++11
COMPILER=		base-clang

MODULES=		devel/cmake

NO_TEST=		Yes

.include <bsd.port.mk>
