# $OpenBSD: $

COMMENT =	expand/collect hostlists

VERSON =	1.20
DISTNAME =	python-hostlist-${VERSON}
PKGNAME =	py-hostlist-${VERSON}
CATEGORIES =	sysutils
HOMEPAGE =	https://www.nsc.liu.se/~kent/python-hostlist/
MASTER_SITES =	${HOMEPAGE}

# GPLv2+
PERMIT_PACKAGE=	Yes

MODULES =	lang/python

MODPY_SETUPTOOLS =	No

FLAVORS =		python3
FLAVOR ?=

NO_TEST =		Yes

.include <bsd.port.mk>
