# $OpenBSD$

VERSION =		1.2.1

COMMENT =		fuzzy-select anything anywhere

DISTNAME =		pick-${VERSION}

CATEGORIES =		sysutils

HOMEPAGE =		https://github.com/thoughtbot/pick

MAINTAINER =		Eric Radman <ericshane@eradman.com>

# MIT
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c ncurses

MASTER_SITES =		https://github.com/thoughtbot/pick/releases/download/v${VERSION}/

CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
